this is my first code doing an exception with python